[book]
authors = ["Joshua Gilman"]
description = "The official book for the `std` framework."
language = "en"
title = "The Standard Book"

[output.html]
additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js"]
edit-url-template = "https://github.com/jmgilman/std-book/edit/master/{path}"
git-repository-url = "https://github.com/jmgilman/std-book"

[preprocessor.mermaid]
command = "mdbook-mermaid"
