name: CI
on:
  pull_request:
    paths-include:
      - "src/**"
      - "book.toml"
  push:
    branches:
      - master
    paths-include:
      - "src/**"
      - "book.toml"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: jmgilman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build